POST http://localhost:8080/api/exercises
Authorization: Bearer eaJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJTa3llZUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3ODExNjQ5NjUsImV4cCI6MTc4MTE2ODU2NX0.8vbsxZu4WZa32K2WBQsko3GtgJ8mHXSyWV9EHmUPlaE
Content-Type: application/json

{
  "name": "Pull Up",
  "muscleGroup": "Back",
  "description": "引體向上"
}