GET http://localhost:8080/api/workouts?date=2026-06-08
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJTa3llZUBnbWFpbC5jb20iLCJpYXQiOjE3ODEwODI3MjAsImV4cCI6MTc4MTA4NjMyMH0.-C0ujnWuU2BHhuCZ_E8gTlHcDu_irebilBB3NCFKiTo